#!/usr/bin/env bash
# Configure Nginx to run as nginx user on port 8080

# Update nginx.conf to run as nginx user
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf

# Change default port from 80 to 8080 in default site config
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80/listen [::]:8080/g' /etc/nginx/sites-available/default

# Kill any running nginx processes
pkill -9 nginx

# Start nginx as nginx user
su -s /bin/bash nginx -c "/usr/sbin/nginx"
