#!/usr/bin/env bash
# Installs and configures Nginx to include a custom HTTP header (X-Served-By) with the server's hostname

# Update package lists and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Get the hostname of the server
HOSTNAME=$(hostname)

# Add X-Served-By header configuration in the default Nginx site
sudo sed -i "/listen 80 default_server;/a \\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
