#!/usr/bin/env bash
# Configures Nginx server to listen on port 80

# Install nginx if it is not installed
apt-get update -y
apt-get install -y nginx

# Force nginx to listen on port 80 by recreating the default server block
cat >/etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

# Restart nginx
service nginx restart
