#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with 301 Moved Permanently

# Install Nginx if it is not already installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Create a custom redirect in the default site configuration
sudo sed -i '/listen 80 default_server;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
